// Icon proxy — all imports go through here, never directly from lucide-react.
// Swapping icon libraries requires changing this file only.
export {
  ChevronRight,
  ChevronLeft,
  ChevronDown,
  ChevronUp,
  X,
  Check,
  AlertCircle,
  Info,
  Loader2,
  ArrowRight,
  ArrowLeft,
  ArrowUpRight,
  Menu,
  Heart,
  Users,
  BookOpen,
  Home,
  Church,
  GraduationCap,
  Copy,
  ExternalLink,
  Mail,
  Phone,
  MapPin,
  Calendar,
  Plus,
  Minus,
  Star,
  Quote,
  HandHeart,
  Handshake,
  Building2,
} from "lucide-react";
